# NumPy

In [34]:
import numpy as np

## 차원 (Dimension)

### 1. 1번 퀘스트

- NumPy 배열의 차원 수 출력

In [35]:
array = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# 차원 수 출력
print(array.ndim)

3


### 2. 2번 퀘스트
- 1차원 배열을 2차원 배열로 변환하여 (2, 3) 형태로 출력


In [36]:
array = np.array([10, 20, 30, 40, 50, 60])

# 배열 변환
reshaped_array = array.reshape(2, 3)

print(reshaped_array)

[[10 20 30]
 [40 50 60]]


### 3. 3번 퀘스트
- 다음 1차원 배열에 새로운 차원을 추가하여 2차원 배열로 변환하고, 최종 배열의 차원 수 출력
  - `newaxis`를 사용해 배열의 차원을 추가하고, 새로운 차원에서의 배열 모양을 확인한 후 최종 차원 수 출력

In [37]:
array = np.array([7, 14, 21])

# 새로운 차원 추가
expanded_array = array[:, np.newaxis]

print(expanded_array)
print(expanded_array.ndim)

[[ 7]
 [14]
 [21]]
2




---



# Shape

### 1. 1번 퀘스트
- 2차원 NumPy 배열의 형태(Shape)를 출력하는 코드 작성

In [38]:
array = np.array([[1, 2, 3], [4, 5, 6]])

print(array.shape)

(2, 3)


### 2. 2번 퀘스트
- 1차원 배열을 (2,3) 형태로 변경한 후, 새로운 배열의 형태를 출력하는 코드 작성

In [39]:
array = np.array([10, 20, 30, 40, 50, 60])
reshaped_array = array.reshape(2, 3)

print(reshaped_array)
print("shape: ", reshaped_array.shape)

[[10 20 30]
 [40 50 60]]
shape:  (2, 3)


### 3. 3번 퀘스트
- 1차원 배열의 형태를 변경하여 (3, 2, 2) 형태로 조정하고, 최종 배열의 형태를 출력하는 코드 작성


In [40]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

reshaped_array = array.reshape(3, 2, 2)
print(reshaped_array)
print("shape: ", reshaped_array.shape)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
shape:  (3, 2, 2)




---



# 데이터 타입 (Data Type)

### 1. 1번 퀘스트
- 아래 NumPy 배열의 데이터 타입을 확인하는 코드 작성

In [41]:
array = np.array([10, 20, 30])

# 배열 타입 확인
print(array.dtype)

int64


### 2. 2번 퀘스트
- 정수형 배열을 부동소수점형 배열로 변환하고, 변환된 배열의 데이터 타입을 출력하는 코드 작성

In [42]:
array = np.array([1, 2, 3])
float_array = array.astype(np.float64)

print(float_array)
print(float_array.dtype)

[1. 2. 3.]
float64


### 3. 3번 퀘스트
- NumPy 배열을 `uint8`로 변환한 후, 메모리 사용량(바이트)을 출력하는 코드작성

In [43]:
array = np.array([100, 200, 300])
uint8_array = array.astype(np.uint8)

print(uint8_array)
print(uint8_array.dtype)

# 메모리 사용량(바이트)
print(uint8_array.nbytes)

[100 200  44]
uint8
3




---



## 인덱싱 (Indexing)

### 1. 1번 퀘스트
- 1차원 배열에서 첫 번재 요소와 마지막 요소를 출력하는 코드 작성

In [44]:
array = np.array([10, 20, 30, 40, 50])

# 첫 번째 요소
print(array[0])

# 마지막 요소
print(array[-1])

10
50


### 2. 2번 퀘스트
- 2차원 배열에서 첫 번째 열과 두 번째 행을 출력하는 코드 작성

In [45]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# 첫 번째 열
print(matrix[:, 0])

# 두 번째 행
print(matrix[1, :])

[1 4 7]
[4 5 6]


### 3. 3번 퀘스트
- 주어진 배열에서 10보다 큰 요소들만 선택하고, 해당 요소들의 인덱스를 출력하는 코드 작성

In [46]:
array = np.array([5, 15, 8, 20, 3, 12])

# 10보다 큰 요소 선택
filtered = array[array > 10]

# 10보다 큰 요소의 인덱스 출력
indices = np.where(array > 10)

print(filtered)
print(indices)

[15 20 12]
(array([1, 3, 5]),)




---



## 연산 (Operation)

### 1. 1번 퀘스트
- NumPy 배열에서 요소별(Element-wise) 덧셈을 수행하는 코드 작성

In [47]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# 요소별 덧셈 수행
print(a + b)

[5 7 9]


### 2. 2번 퀘스트
- NumPy 배열에서 브로드캐스팅을 활용해 각 행에 [1, 2, 3]을 더하는 코드 작성

In [48]:
matrix = np.array([[10, 20, 30], [40, 50, 60]])
vector = np.array([1, 2, 3])

# 브로드캐스팅 활용 덧셈
print(matrix + vector)

[[11 22 33]
 [41 52 63]]


### 3. 3번 퀘스트
- 주어진 2차원 NumPy 배열에 대해, 축(axis)을 기준으로 최댓값을 구하고 최종 배열의 차원을 출력하는 코드 작성

In [49]:
array = np.array([[3, 7, 2], [8, 4, 6]])

# 축 기준으로 최댓값 구하기
max_axis_0 = np.max(array, axis=0)
max_axis_1 = np.max(array, axis=1)

print(max_axis_0)
print(max_axis_1)

# 최종 배열의 차원 출력
print(max_axis_0.ndim)
print(max_axis_1.ndim)

[8 7 6]
[7 8]
1
1




---



## 유니버셜 함수 (Universal Function)

### 1. 1번 퀘스트
- NumPy의 유니버셜 함수를 사용하여 모든 요소를 제곱한 결과를 출력하는 코드 작성

In [50]:
array = np.array([1, 2, 3, 4])

# 요소의 거듭제곱 연산
print(np.power(array, 2))

[ 1  4  9 16]


### 2. 2번 퀘스트
- 두 배열의 요소별 합을 계산
- 결과를 새로운 배열이 아닌 기존 배열에 저장하는 코드 작성

In [51]:
array1 = np.array([10, 20, 30])
array2 = np.array([1, 2, 3])

# 요소별 합을 기존 배열에 저장
np.add(array1, array2, out=array1)

print(array1)

[11 22 33]


### 3. 3번 퀘스트
- NumPy 유니버셜 함수를 사용해 요소별로 자연로그(log)를 계산
- 특정 조건(`log 값 >1`)을 만족하는 요소만 출력하는 코드 작성

In [52]:
array = np.array([1, np.e, 10, 100])

# 자연로그 계산
log_array = np.log(array)

# 조건(log 값 > 1) 만족 요소 출력
filtered_array = log_array[log_array > 1]

print(log_array)
print(filtered_array)

[0.         1.         2.30258509 4.60517019]
[2.30258509 4.60517019]
